services:
  - type: web
    name: ticketing-system
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    branch: main
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m